# Generated by Django 5.2.8 on 2026-04-12 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='posts_commentlike_user_comment_uniq'),
        ),
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='posts_postlike_user_post_uniq'),
        ),
    ]
