# Generated by Django 5.2.8 on 2025-11-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_people_tags_alter_post_content_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentlike',
            options={'verbose_name': 'Comment Like', 'verbose_name_plural': 'Comment Likes'},
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={'verbose_name': 'Post Like', 'verbose_name_plural': 'Post Likes'},
        ),
    ]
