# Generated by Django 5.2.8 on 2026-01-27 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('background', models.ImageField(blank=True, default='default/default_bg.png', null=True, upload_to='backgrounds/', verbose_name='Background')),
                ('is_group', models.BooleanField(default=False, verbose_name='Is group chat')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('users', models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(blank=True, max_length=4096, null=True, verbose_name='Text')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messenger.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emoji', models.CharField(choices=[('😀', 'grinning_face'), ('😂', 'face_with_tears_of_joy'), ('🤣', 'rolling_on_the_floor_laughing'), ('😊', 'smiling_face_with_smiling_eyes'), ('😍', 'smiling_face_with_heart-eyes'), ('😘', 'face_blowing_a_kiss'), ('😎', 'smiling_face_with_sunglasses'), ('😉', 'winking_face'), ('😏', 'smirking_face'), ('😢', 'crying_face'), ('😭', 'loudly_crying_face'), ('😡', 'enraged_face'), ('🤯', 'exploding_head'), ('😱', 'face_screaming_in_fear'), ('🥺', 'pleading_face'), ('😅', 'grinning_face_with_sweat'), ('🤔', 'thinking_face'), ('🤨', 'face_with_raised_eyebrow'), ('🙄', 'face_with_rolling_eyes'), ('😴', 'sleeping_face'), ('👍', 'thumbs_up'), ('👎', 'thumbs_down'), ('🙏', 'folded_hands'), ('👏', 'clapping_hands'), ('💪', 'flexed_biceps'), ('🔥', 'fire'), ('💯', 'hundred_points'), ('💔', 'broken_heart'), ('❤️', 'red_heart'), ('💖', 'sparkling_heart'), ('🎉', 'party_popper'), ('✨', 'sparkles'), ('😇', 'smiling_face_with_halo'), ('🥳', 'partying_face'), ('🤡', 'clown_face')], max_length=10, verbose_name='Emoji')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='messenger.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reaction',
                'verbose_name_plural': 'Reactions',
                'ordering': ['created_at'],
                'unique_together': {('message', 'user')},
            },
        ),
    ]
