# Generated by Django 5.2.8 on 2025-11-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['created_at'], 'verbose_name': 'Chat', 'verbose_name_plural': 'Chats'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='reaction',
            options={'ordering': ['created_at'], 'verbose_name': 'Reaction', 'verbose_name_plural': 'Reactions'},
        ),
        migrations.AlterField(
            model_name='chat',
            name='background',
            field=models.ImageField(blank=True, default='default/default_bg.png', null=True, upload_to='backgrounds/', verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_group',
            field=models.BooleanField(default=False, verbose_name='Is group chat'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='emoji',
            field=models.CharField(choices=[('😀', 'grinning_face'), ('😂', 'face_with_tears_of_joy'), ('🤣', 'rolling_on_the_floor_laughing'), ('😊', 'smiling_face_with_smiling_eyes'), ('😍', 'smiling_face_with_heart-eyes'), ('😘', 'face_blowing_a_kiss'), ('😎', 'smiling_face_with_sunglasses'), ('😉', 'winking_face'), ('😏', 'smirking_face'), ('😢', 'crying_face'), ('😭', 'loudly_crying_face'), ('😡', 'enraged_face'), ('🤯', 'exploding_head'), ('😱', 'face_screaming_in_fear'), ('🥺', 'pleading_face'), ('😅', 'grinning_face_with_sweat'), ('🤔', 'thinking_face'), ('🤨', 'face_with_raised_eyebrow'), ('🙄', 'face_with_rolling_eyes'), ('😴', 'sleeping_face'), ('👍', 'thumbs_up'), ('👎', 'thumbs_down'), ('🙏', 'folded_hands'), ('👏', 'clapping_hands'), ('💪', 'flexed_biceps'), ('🔥', 'fire'), ('💯', 'hundred_points'), ('💔', 'broken_heart'), ('❤️', 'red_heart'), ('💖', 'sparkling_heart'), ('🎉', 'party_popper'), ('✨', 'sparkles'), ('😇', 'smiling_face_with_halo'), ('🥳', 'partying_face'), ('🤡', 'clown_face')], max_length=10, verbose_name='Emoji'),
        ),
    ]
