# Generated by Django 5.2.8 on 2026-01-19 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('new_messenger_message', 'New messenger message'), ('message_reaction', 'Message reaction'), ('new_post', 'New post'), ('post_like', 'Post like'), ('new_comment', 'New comment'), ('comment_like', 'Comment like'), ('tagged_in_post', ' Tagged in post'), ('new_follower', 'New follower'), ('new_board_messsage', ' New board message'), ('join_board', 'Join board')], max_length=100, verbose_name='Event Type')),
                ('target_type', models.CharField(choices=[('user', 'User'), ('post', 'Post'), ('comment', 'Comment'), ('reaction', 'Reaction'), ('message', 'Message'), ('board', 'Board')], max_length=100, verbose_name='Target Type')),
                ('target_id', models.IntegerField(verbose_name='Target ID')),
                ('is_read', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
